import mutations from "./mutations";
import getters from "./getters";
import actions from "./actions";
import { createStore } from "vuex";

const store = createStore({
  state() {
    return {
      items: [
        {id: 1,name: "Cursed Sword (+1)",damage: 54,rate: 1,type: "Sword",class: "Low Class",img:'/upgradeMe/cursedSword.png'},
        {id: 2,name: "Cursed Sword (+2)",damage: 57,rate: 2,type: "Sword",class: "Low Class",img:'/upgradeMe/cursedSword.png'},
        {id: 3,name: "Cursed Sword (+3)",damage: 60,rate: 3,type: "Sword",class: "Low Class",img:'/upgradeMe/cursedSword.png'},
        {id: 4,name: "Cursed Sword (+4)",damage: 63,rate: 4,type: "Sword",class: "Low Class",img:'/upgradeMe/cursedSword.png'},
        {id: 5,name: "Cursed Sword (+5)",damage: 67,rate: 5,type: "Sword",class: "Low Class",img:'/upgradeMe/cursedSword.png'},
        {id: 11,name: "Scimitar (+1)",damage: 57,rate: 1,type: "Sword",class: "Low Class",img:'/upgradeMe/scimitar.png'},
        {id: 12,name: "Scimitar (+2)",damage: 60,rate: 2,type: "Sword",class: "Low Class",img:'/upgradeMe/scimitar.png'},
        {id: 13,name: "Scimitar (+3)",damage: 63,rate: 3,type: "Sword",class: "Low Class",img:'/upgradeMe/scimitar.png'},
        {id: 14,name: "Scimitar (+4)",damage: 66,rate: 4,type: "Sword",class: "Low Class",img:'/upgradeMe/scimitar.png'},
        {id: 15,name: "Scimitar (+5)",damage: 70,rate: 5,type: "Sword",class: "Low Class",img:'/upgradeMe/scimitar.png'},
        {id: 21,name: "Mukage (+1)",damage: 60,rate: 1,type: "Sword",class: "Middle Class",img:'/upgradeMe/mukage.png'},
        {id: 22,name: "Mukage (+2)",damage: 63,rate: 2,type: "Sword",class: "Middle Class",img:'/upgradeMe/mukage.png'},
        {id: 23,name: "Mukage (+3)",damage: 66,rate: 3,type: "Sword",class: "Middle Class",img:'/upgradeMe/mukage.png'},
        {id: 24,name: "Mukage (+4)",damage: 69,rate: 4,type: "Sword",class: "Middle Class",img:'/upgradeMe/mukage.png'},
        {id: 25,name: "Mukage (+5)",damage: 73,rate: 5,type: "Sword",class: "Middle Class",img:'/upgradeMe/mukage.png'},
        {id: 31,name: "War Scythe (+1)",damage: 65,rate: 1,type: "Sword",class: "High Class",img:'/upgradeMe/warScythe.png'},
        {id: 32,name: "War Scythe (+2)",damage: 68,rate: 2,type: "Sword",class: "High Class",img:'/upgradeMe/warScythe.png'},
        {id: 33,name: "War Scythe (+3)",damage: 71,rate: 3,type: "Sword",class: "High Class",img:'/upgradeMe/warScythe.png'},
        {id: 34,name: "War Scythe (+4)",damage: 74,rate: 4,type: "Sword",class: "High Class",img:'/upgradeMe/warScythe.png'},
        {id: 35,name: "War Scythe (+5)",damage: 79,rate: 5,type: "Sword",class: "High Class",img:'/upgradeMe/warScythe.png'},
        {id: 41,name: "Kukry (+1)",damage: 32,rate: 1,type: "Dagger",class: "Low Class",img:'/upgradeMe/kukry.png'},
        {id: 42,name: "Kukry (+2)",damage: 34,rate: 2,type: "Dagger",class: "Low Class",img:'/upgradeMe/kukry.png'},
        {id: 43,name: "Kukry (+3)",damage: 36,rate: 3,type: "Dagger",class: "Low Class",img:'/upgradeMe/kukry.png'},
        {id: 44,name: "Kukry (+4)",damage: 38,rate: 4,type: "Dagger",class: "Low Class",img:'/upgradeMe/kukry.png'},
        {id: 45,name: "Kukry (+5)",damage: 40,rate: 5,type: "Dagger",class: "Low Class",img:'/upgradeMe/kukry.png'},
        {id: 51,name: "Dragon Teeth (+1)",damage: 34,rate: 1,type: "Dagger",class: "Middle Class",img:'/upgradeMe/dragonTeeth.png'},
        {id: 52,name: "Dragon Teeth (+2)",damage: 36,rate: 2,type: "Dagger",class: "Middle Class",img:'/upgradeMe/dragonTeeth.png'},
        {id: 53,name: "Dragon Teeth (+3)",damage: 38,rate: 3,type: "Dagger",class: "Middle Class",img:'/upgradeMe/dragonTeeth.png'},
        {id: 54,name: "Dragon Teeth (+4)",damage: 40,rate: 4,type: "Dagger",class: "Middle Class",img:'/upgradeMe/dragonTeeth.png'},
        {id: 55,name: "Dragon Teeth (+5)",damage: 43,rate: 5,type: "Dagger",class: "Middle Class",img:'/upgradeMe/dragonTeeth.png'},
        {id: 61,name: "Twin Fang (+1)",damage: 37,rate: 1,type: "Dagger",class: "High Class",img:'/upgradeMe/twinFang.png'},
        {id: 62,name: "Twin Fang (+2)",damage: 40,rate: 2,type: "Dagger",class: "High Class",img:'/upgradeMe/twinFang.png'},
        {id: 63,name: "Twin Fang (+3)",damage: 43,rate: 3,type: "Dagger",class: "High Class",img:'/upgradeMe/twinFang.png'},
        {id: 64,name: "Twin Fang (+4)",damage: 46,rate: 4,type: "Dagger",class: "High Class",img:'/upgradeMe/twinFang.png'},
        {id: 65,name: "Twin Fang (+5)",damage: 50,rate: 5,type: "Dagger",class: "High Class",img:'/upgradeMe/twinFang.png'},
        {id: 71,name: "Hunt Bow (+1)",damage: 57,rate: 1,type: "Bow",class: "Low Class",img:'/upgradeMe/huntBow.png'},
        {id: 72,name: "Hunt Bow (+2)",damage: 61,rate: 2,type: "Bow",class: "Low Class",img:'/upgradeMe/huntBow.png'},
        {id: 73,name: "Hunt Bow (+3)",damage: 65,rate: 3,type: "Bow",class: "Low Class",img:'/upgradeMe/huntBow.png'},
        {id: 74,name: "Hunt Bow (+4)",damage: 69,rate: 4,type: "Bow",class: "Low Class",img:'/upgradeMe/huntBow.png'},
        {id: 75,name: "Hunt Bow (+5)",damage: 74,rate: 5,type: "Bow",class: "Low Class",img:'/upgradeMe/huntBow.png'},
        {id: 81,name: "Swift Wing (+1)",damage: 61,rate: 1,type: "Bow",class: "Middle Class",img:'/upgradeMe/swiftWing.png'},
        {id: 82,name: "Swift Wing (+2)",damage: 65,rate: 2,type: "Bow",class: "Middle Class",img:'/upgradeMe/swiftWing.png'},
        {id: 83,name: "Swift Wing (+3)",damage: 69,rate: 3,type: "Bow",class: "Middle Class",img:'/upgradeMe/swiftWing.png'},
        {id: 84,name: "Swift Wing (+4)",damage: 73,rate: 4,type: "Bow",class: "Middle Class",img:'/upgradeMe/swiftWing.png'},
        {id: 85,name: "Swift Wing (+5)",damage: 78,rate: 5,type: "Bow",class: "Middle Class",img:'/upgradeMe/swiftWing.png'},
        {id: 91,name: "Moon Fang (+1)",damage: 66,rate: 1,type: "Bow",class: "High Class",img:'/upgradeMe/moonFang.png'},
        {id: 92,name: "Moon Fang (+2)",damage: 71,rate: 2,type: "Bow",class: "High Class",img:'/upgradeMe/moonFang.png'},
        {id: 93,name: "Moon Fang (+3)",damage: 76,rate: 3,type: "Bow",class: "High Class",img:'/upgradeMe/moonFang.png'},
        {id: 94,name: "Moon Fang (+4)",damage: 81,rate: 4,type: "Bow",class: "High Class",img:'/upgradeMe/moonFang.png'},
        {id: 95,name: "Moon Fang (+5)",damage: 87,rate: 5,type: "Bow",class: "High Class",img:'/upgradeMe/moonFang.png'},
      ],
      inventory : [],
      item : null,
      upgradedItem : null,
      isScrollSlotted : false,
      isUpgraded : false,
      progressing : false,
    };
  },
  getters: getters,
  mutations: mutations,
  actions: actions,
});

export default store;
